# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lient.proto\x1a\x1bgoogle/protobuf/empty.proto\"\"\n\x10JoinNotification\x12\x0e\n\x06player\x18\x01 \x01(\t\"#\n\x11LeaveNotification\x12\x0e\n\x06player\x18\x01 \x01(\t\"*\n\x12\x41\x63tionNotification\x12\x14\n\x0cnotification\x18\x01 \x01(\t\"\x14\n\x04Role\x12\x0c\n\x04role\x18\x01 \x01(\t\"#\n\x10\x41vailableActions\x12\x0f\n\x07\x61\x63tions\x18\x01 \x03(\t\"\x0e\n\x0cLivezRequest\"\x0f\n\rLivezResponse2\xdb\x02\n\x06\x43lient\x12\x39\n\nNotifyJoin\x12\x11.JoinNotification\x1a\x16.google.protobuf.Empty\"\x00\x12;\n\x0bNotifyLeave\x12\x12.LeaveNotification\x1a\x16.google.protobuf.Empty\"\x00\x12=\n\x0cNotifyAction\x12\x13.ActionNotification\x1a\x16.google.protobuf.Empty\"\x00\x12+\n\x08SendRole\x12\x05.Role\x1a\x16.google.protobuf.Empty\"\x00\x12\x43\n\x14SendAvailableActions\x12\x11.AvailableActions\x1a\x16.google.protobuf.Empty\"\x00\x12(\n\x05Livez\x12\r.LivezRequest\x1a\x0e.LivezResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JOINNOTIFICATION._serialized_start=45
  _JOINNOTIFICATION._serialized_end=79
  _LEAVENOTIFICATION._serialized_start=81
  _LEAVENOTIFICATION._serialized_end=116
  _ACTIONNOTIFICATION._serialized_start=118
  _ACTIONNOTIFICATION._serialized_end=160
  _ROLE._serialized_start=162
  _ROLE._serialized_end=182
  _AVAILABLEACTIONS._serialized_start=184
  _AVAILABLEACTIONS._serialized_end=219
  _LIVEZREQUEST._serialized_start=221
  _LIVEZREQUEST._serialized_end=235
  _LIVEZRESPONSE._serialized_start=237
  _LIVEZRESPONSE._serialized_end=252
  _CLIENT._serialized_start=255
  _CLIENT._serialized_end=602
# @@protoc_insertion_point(module_scope)
